# 异常体系


![](http://p5s0bbd0l.bkt.clouddn.com/exception1.jpg)


#### Error和Exception

- Error表示系统级系统，是Java运行环境内部错误或者硬件错误，不能指望程序来处理这样的问题，除了退出运行外没有选择，它是JVM抛出的。

- Exception表示程序需要捕捉、处理的异常，是由于程序设计不完善出现的问题，程序必须处理的问题。


#### Exception

Java提供了两类异常：RuntimeException和CheckedException

- 一般异常（CheckedException）：主要是IOException和SQLException等，对于这些异常，JVM要求我们必须要对其进行catch异常。

- 运行时异常（RuntimeException）：我们一般不处理，当出现了这类异常的时候，异常会被JVM接管，比如常见的NullPointerException、ClassNotFoundException和ArrayIndexOutOfBoundsExceeption等等。

出现运行时异常的时候，程序会将异常一直向上抛，一直遇到处理异常的代码。若到了最上层还没有被捕获，在多线程的时候会被Thread.run()抛出，如果不是多线程，就会被main.run()抛出。抛出之后，Thread/main对应的程序会被终止。

#### 异常处理机制

在Java中，每个异常都是一个对象，它都是Throwable或其子类的的实例。当一个方法出现异常之后，就会抛出一个异常对象，该对象含有异常信息。

- try：一块用来预防异常的程序
- catch：捕获异常
- finally：确保无论是否发生异常都会执行的代码段
- throw：用来明确抛出的一个异常
- throws：用来表示一个成员函数可能会抛出的各种异常

#### 对异常进行的处理

- 尽量避免RuntimeException：比如可能出现的空指针异常，数组越界问题
- 对于catch块的代码要打印日志，并且不能让数据库信息返回给客户端
- 在I/O处理和SQL连接之后，及时在finally块中关闭，这正是CheckedException存在的意义

#### 两个关键字

- throws：总是出现在函数头中，表明方法可能抛出的各种异常
- throw：出现在方法体中，相当于return语句


#### 三个关键字

- final：用于声明，表示变量值不可以改变，方法不可以覆盖，类不可继承
- finally：与try合用，表示finally块中的代码一定会执行
- finalize：修饰对象类的一个方法，在GC阶段可能会被调用

#### JDK1.7的新特性

- 对于Error和Exception的处理，一个try语句块，可以由catch处理

```java
	try{
		//...
	}catch(InterruptedException | RuntimeException | OutOfMemoryError e){
		//TODO
	}
```
- try-with-resource块，避免了一大坨代码，其实底层是现实，增加finally语句块，对I/O文件和SQL连接，做了封装

```java
    try(Selector selector = Selector.open()){
        //...
    }catch (IOException e){
        //TOD
    }
```

#### 重写方法

- 如果父类没有抛出异常，子类重写的方法也不准抛出异常
- 子类抛出异常的范围，不允许超出父类的抛出异常的范围

#### 异常链

指的是在进行一个异常处理的时候，抛出了另外一个异常，由此产生了一个异常链条。比如可以用于将CheckedException封装为RuntimeExcetion，也就是改变异常类型。

```java
	try{
		//...
	}catch(SQLException e){
		Throwable throwable = new ServletException("data error");
		throwable.initCause(e);
		throw throwable;
	}
```

当捕获到ServletException异常的时候，可以获取到原始异常，这种异常包装技术，可以让用户抛出子系统中的高级异常，而不会丢失原始异常的小细节。

```
	Throwable throwable = e.getCause();
```
